### ISSUE TITLE
Añadir funcionalidades al programa inicial (Hito - 20 de abril)

### ISSUE THREAD

**Issue by raquelcedazo** [aigora/twQ103_1920-twq103-comete-el-rosco#1]
Hola:

Os comento lo que veo de vuestra primera entrega y os propongo el desarrollo de más funcionalidad.

El menú es bastante básico y además deberíais hacerlo para que el menú se repita indefinidamente.

Debéis describir en el archivo principal los "Objetivos del trabajo" los detalles de cada una de las funcionalidades porque no están claras.

El hito que os propongo para el 20 de abril es que creéis un fichero con todos los usuarios o preguntas y que se muestren al seleccionar las opciones correspondientes. Os aconsejo que almacenéis los datos en vectores de estructuras.

Además de esto, os animo a que sigáis programando más funcionalidades, como dar de alta nuevos usuarios, elegir una pregunta concreta, añadir una clasificación de usuarios, etc.

Un saludo y buenas vacaciones.

**Comment by raquelcedazo** [comment]
Hay muchos ficheros .c y .cpp y no sé cuál es el definitivo. Dejad sólo el que vale.

**Comment by RicardoSuero** [comment]
Hecho
